# Generated by Django 4.0 on 2021-12-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('c_type', models.CharField(max_length=100)),
                ('desc', models.TextField(default='course description')),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
