# Generated by Django 4.0 on 2022-03-14 10:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_user_type'),
        ('dss', '0003_course_c_department_course_c_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dss.course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.customuser')),
            ],
            options={
                'ordering': ['user_rating'],
            },
        ),
    ]
