# Generated by Django 4.0 on 2022-03-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dss', '0004_course_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='c_assignments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='c_content',
            field=models.TextField(default='content'),
        ),
        migrations.AddField(
            model_name='course',
            name='c_final',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='c_participation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='c_prereq',
            field=models.CharField(default='Nil', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='c_project',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='c_quiz',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='c_units',
            field=models.IntegerField(default=0),
        ),
    ]
